### PR TITLE
add sync

### PR DESCRIPTION
**Pull request by cellvia**
add sync method

### CODE REVIEW

**Comment by thlorenz** [comment]
Thanks, this is awesome!
I'll probably be the next one to need the `sync` version :)

However could you please add some tests for your feature along the lines of https://github.com/thlorenz/mothership/blob/master/test/mothership.js ?

You could copy `test/mothership.js` to `test/mothership-sync.js` and then adjust all the tests to use the `sync` function.
This way we ensure that sync and async behave the same way.

Thanks.

**Comment by cellvia** [comment]
oh woops, didnt see it had tests ;-)  will add soon!

**Comment by cellvia** [comment]
ok, tests added!!

**Comment by thlorenz** [comment]
Thanks, published as `v0.3.0`.

**Pull request closed without merging**
